### ISSUE TITLE
User is able to add themselves to a unit

### ISSUE THREAD

**Issue by purgat0ry** [phansiri/innovation_challenge_testing#24]
As a user, I should be able to add myself to an existing unit, in order to start submitting exercises for that unit.

**Comment by breencp** [comment]
To elaborate, the only time when someone adds themselves to a unit is upon creation of a new exercise where they are the highest echelon.  Anyone else wishing to join must be granted permissions from someone already assigned to a unit within the exercise.  Permissions can be delegated down or within the same unit, but not up.

**Comment by Master-Minja** [comment]
my understanding is this issue is obsolete now, can i close it
