### ISSUE TITLE
User is able to create a new unit

### ISSUE THREAD

**Issue by purgat0ry** [phansiri/innovation_challenge_testing#25]
As a user, I should be able to create a new unit if one does not already exist for my command.

**Comment by breencp** [comment]
To add context, this is done from the new exercise screen.  When creating a new exercise, if the unit drop down does not contain the unit you need, a ‘create new unit’ option is available.  This is also where a logistician is assigned to the unit, so new unit creation would rarely, if ever, be done by the user of that unit.  It will typically be done by the planner creating the exercise.
