### ISSUE TITLE
Clicking an exercise with multiple copies in DB causes error

### ISSUE THREAD

**Issue by purgat0ry** [phansiri/innovation_challenge_testing#61]
![image](https://user-images.githubusercontent.com/18694882/117674544-b6a82780-b1e6-11eb-99f0-ec29c5e8b5f4.png)
![image](https://user-images.githubusercontent.com/18694882/117674581-bdcf3580-b1e6-11eb-91dc-9662b903a487.png)

**Comment by breencp** [comment]
All tables are using the Django auto increment ID field for a primary key.  Many tables enforce unique records with a combination of attributes, and only sometimes a single attribute.  Reference the model.py file for 'constraint = UniqueConstraint...' to ensure table lookups are using the right combination of fields in all lookups.

**Comment by purgat0ry** [comment]
The lookup likely needs to get mapped to the exercise id instead of the name field. @merryfistmas
